-- =============================================================================
-- Cyber Threat Hunting Agent - Shared Database Schema
-- =============================================================================
-- OWNERSHIP RULES:
--   logs    table  --> Written by: backend/api.py | Read by: agent, dashboard
--   alerts  table  --> Written by: agent/main.py  | Read by: dashboard
-- =============================================================================

-- Drop tables if they exist (for clean re-initialization)
DROP TABLE IF EXISTS alerts;
DROP TABLE IF EXISTS logs;

-- -----------------------------------------------------------------------------
-- LOGS TABLE
-- Every incoming request to the Victim App is written here by the backend.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS logs (
    id           INTEGER  PRIMARY KEY AUTOINCREMENT,
    timestamp    DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now')),
    event_type   TEXT     NOT NULL,   -- 'login_attempt', 'page_access', 'api_call'
    method       TEXT,                -- 'GET', 'POST', 'PUT', 'DELETE'
    endpoint     TEXT,                -- '/login', '/admin', '/config', '/internal'
    username     TEXT,                -- username if applicable (NULL for anonymous)
    ip           TEXT     NOT NULL,   -- source IP address of the request
    status_code  INTEGER,             -- HTTP response code: 200, 401, 403, 404, 500
    status       TEXT                 -- 'success', 'fail', 'blocked'
);

-- Index on ip + timestamp for fast agent rule queries
CREATE INDEX IF NOT EXISTS idx_logs_ip_time     ON logs (ip, timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_event_time  ON logs (event_type, timestamp);
CREATE INDEX IF NOT EXISTS idx_logs_endpoint    ON logs (endpoint, timestamp);

-- -----------------------------------------------------------------------------
-- ALERTS TABLE
-- Every confirmed threat detected by the agent is written here.
-- -----------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS alerts (
    id              INTEGER  PRIMARY KEY AUTOINCREMENT,
    timestamp       DATETIME NOT NULL DEFAULT (strftime('%Y-%m-%d %H:%M:%S', 'now')),
    threat_type     TEXT     NOT NULL,  -- 'Brute Force Attack', 'Endpoint Reconnaissance', etc.
    risk_level      TEXT     NOT NULL,  -- 'LOW', 'MEDIUM', 'HIGH', 'CRITICAL'
    confidence      INTEGER  NOT NULL,  -- 0-100 score from the rules engine
    source_ip       TEXT     NOT NULL,  -- IP address that triggered the alert
    triggered_rules TEXT,               -- JSON array: ["rule_high_login_failure", ...]
    details         TEXT,               -- JSON object with supporting evidence/counts
    llm_hypothesis  TEXT,               -- Hypothesis sentence generated by Ollama
    llm_report      TEXT                -- Human-readable incident report from Ollama
);

-- Index for dashboard to quickly fetch recent/unread alerts
CREATE INDEX IF NOT EXISTS idx_alerts_time      ON alerts (timestamp);
CREATE INDEX IF NOT EXISTS idx_alerts_ip_type   ON alerts (source_ip, threat_type, timestamp);
